import { CoffeeEntry } from "./types";

export const FALLBACK_COFFEES: CoffeeEntry[] = [
  {
    id: "demo-1",
    roaster: "Demo Roaster",
    coffee: "Ethiopia Yirgacheffe Kochere",
    type: "Single Origin",
    process: "Washed",
    tastingNotes: ["Bergamot", "Peach", "Jasmine"],
    price: "$22.00",
    date: new Date().toISOString(),
    link: "#",
  },
  {
    id: "demo-2",
    roaster: "Demo Roaster",
    coffee: "Colombia El Paraiso",
    type: "Single Origin",
    process: "Anaerobic",
    tastingNotes: ["Strawberry", "Chocolate", "Tropical"],
    price: "$24.00",
    date: new Date().toISOString(),
    link: "#",
  },
  {
    id: "demo-3",
    roaster: "Demo Roaster",
    coffee: "Nightcap Blend",
    type: "Blend",
    process: "Washed",
    tastingNotes: ["Caramel", "Chocolate", "Nutty"],
    price: "$18.00",
    date: new Date().toISOString(),
    link: "#",
  },
  {
    id: "demo-4",
    roaster: "Demo Roaster",
    coffee: "Kenya Nyeri AA",
    type: "Single Origin",
    process: "Washed",
    tastingNotes: ["Blackcurrant", "Tomato", "Brown Sugar"],
    price: "$26.00",
    date: new Date().toISOString(),
    link: "#",
  },
  {
    id: "demo-5",
    roaster: "Demo Roaster",
    coffee: "Guatemala Huehuetenango",
    type: "Single Origin",
    process: "Honey",
    tastingNotes: ["Apple", "Honey", "Milk Chocolate"],
    price: "$20.00",
    date: new Date().toISOString(),
    link: "#",
  },
];
